In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv('homeprices.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [3]:
import math
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

4

In [4]:
df.bedrooms.fillna(median_bedrooms, inplace=True)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [5]:
reg = linear_model.LinearRegression()
reg.fit(df[['area', 'bedrooms', 'age']], df.price)

LinearRegression()

In [6]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [7]:
reg.intercept_

221323.00186540408

In [8]:
reg.predict([[3000, 3, 40]])

array([498408.25158031])

In [9]:
reg.predict([[2500, 4, 5]])

array([578876.03748933])

In [13]:
pip install word2number

  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5586 sha256=ddbfbfbfd31d797bc8d7800d044d0d8fe704cba6ed43c2451177817e582c41bb
  Stored in directory: c:\users\aatwa\appdata\local\pip\cache\wheels\cb\f3\5a\d88198fdeb46781ddd7e7f2653061af83e7adb2a076d8886d6
Successfully built word2number
Note: you may need to restart the kernel to use updated packages.


In [14]:
from word2number import w2n

In [15]:
df_train = pd.read_csv('hiring.csv')
df_train

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [20]:
df_train.experience.fillna('zero', inplace=True)
df_train

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [29]:
experience_list = []
for s in df_train.experience:
    experience_list.append(w2n.word_to_num(s))
    
df_train.experience = experience_list

Use df_train.experience = df_train.experience.apply(w2n.word_to_num)

In [30]:
test_score_median = math.floor(df_train['test_score(out of 10)'].median())
test_score_median

8

In [31]:
df_train['test_score(out of 10)'].fillna(test_score_median, inplace=True)
df_train

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [39]:
model = linear_model.LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1)
model.fit(df_train[['experience','test_score(out of 10)','interview_score(out of 10)']], df_train['salary($)'])

LinearRegression(n_jobs=1)

In [40]:
model.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [41]:
model.intercept_

17737.26346433771

In [42]:
model.predict([[2, 9, 6]])

array([53205.96797671])

In [37]:
model.predict([[12, 10, 10]])

array([92002.18340611])