In [103]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [104]:
df1 = pd.read_csv('ex2data1.txt', names=range(3))
df1.head()

0          1  2
0  34.623660  78.024693  0
1  30.286711  43.894998  0
2  35.847409  72.902198  0
3  60.182599  86.308552  1
4  79.032736  75.344376  1

In [105]:
X = np.matrix([df1[0], df1[1]])
y = np.matrix(df1[2])

In [106]:
X = X.transpose()

In [107]:
print(X.shape)

(100, 2)


In [108]:
y = y.transpose()

In [109]:
print(y.shape)

(100, 1)


In [110]:
m, n = X.shape
print(m, n)

100 2


In [111]:
def plotData(X, y):
    figure = plt.Figure
    pos = np.array(y==1)
    print(X[pos[:, 0], 1][:, 0])
    plt.scatter(X[pos[:, 0], 1], X[pos[:, 0], 1], marker='+', label='Admitted')
    # plt.scatter(X[neg, 0], X[neg, 1], marker='o', color='yellow', label='Not Admitted')
    plt.xlabel('Exam 1 Score')
    plt.ylabel('Exam 2 Score')
    plt.legend()

In [112]:
# plotData(X, y)

In [113]:
X = np.append(np.ones((m, 1)), X, axis=1)

In [114]:
X.shape

(100, 3)

In [115]:
initial_theta = np.zeros((n+1, 1))

In [116]:
initial_theta

array([[0.],
       [0.],
       [0.]])

In [117]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

In [118]:
sigmoid(np.array([0]))

array([0.5])

In [119]:
def costFunction(theta, X, y):
    m = len(y)
    J = 0
    z = np.matmul(X, theta)
    h = sigmoid(z)

    term1 = np.multiply(-1 * y, np.log(h))
    term2 = np.multiply((1-y), np.log((1-h)))
    
    J = 1/m * np.sum(term1-term2)

    # error = np.subtract(h, y)

    # grad = 1/m * (X.transpose() * error)
    return J


In [120]:
def gradientFunction(theta, X, y):
    m = len(y)
    grad = np.zeros(m)

    z = np.matmul(X, theta)
    h = sigmoid(z)
    error = np.subtract(h, y)

    grad = 1/m * (X.transpose() * error)
    print(grad.dtype)
    return grad.flatten()

In [121]:
J = costFunction(initial_theta, X, y)
J

0.6931471805599453

In [122]:
grad = gradientFunction(initial_theta, X, y)
grad

float64


matrix([[ -0.1       , -12.00921659, -11.26284221]])

In [123]:
print("Cost at initial theta (zeros): {}\n".format(J))
print('Expected cost (approx): 0.693\n')
print('Gradient at initial theta (zeros): \n{}\n'.format(grad))
print('Expected gradients (approx):\n -0.1000\n -12.0092\n -11.2628\n')

Cost at initial theta (zeros): 0.6931471805599453

Expected cost (approx): 0.693

Gradient at initial theta (zeros): 
[[ -0.1        -12.00921659 -11.26284221]]

Expected gradients (approx):
 -0.1000
 -12.0092
 -11.2628



In [124]:
test_theta = np.array([[-24], [0.2], [0.2]])
test_theta

array([[-24. ],
       [  0.2],
       [  0.2]])

In [125]:
J_test = costFunction(test_theta, X, y)
grad_test = gradientFunction(test_theta, X, y)

float64


In [126]:
print("\nCost at test theta: %f\n" % (J_test))
print("Expected cost (approx): 0.218\n")
print("Gradient at test theta: \n{}\n".format(grad_test))
print("Expected gradients (approx):\n 0.043\n 2.566\n 2.647\n")


Cost at test theta: 0.218330

Expected cost (approx): 0.218

Gradient at test theta: 
[[0.04290299 2.56623412 2.64679737]]

Expected gradients (approx):
 0.043
 2.566
 2.647



In [127]:
initial_theta = np.zeros((n+1, 1))
initial_theta.shape

(3, 1)

In [128]:
from scipy.optimize import minimize

In [129]:
res = minimize(costFunction, initial_theta, args=(X, y), method='Newton-CG', jac=gradientFunction, options={'maxiter': 1000})

float64


C:\Users\slcccc\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:86: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()