In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_iris

iris = load_iris()

In [7]:
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score

kf = StratifiedKFold(n_splits=5)
kf.split(iris.data, iris.target)
cross_val_score(LogisticRegression(max_iter=1000), iris.data, iris.target, cv=3)

array([0.98, 0.96, 0.98])

In [8]:
cross_val_score(SVC(), iris.data, iris.target, cv=3)

array([0.96, 0.98, 0.94])

In [9]:
cross_val_score(RandomForestClassifier(n_estimators=40), iris.data, iris.target, cv=3)

array([0.98, 0.94, 0.98])

In [10]:
cross_val_score(RandomForestClassifier(n_estimators=50), iris.data, iris.target, cv=3)

array([0.98, 0.92, 0.96])