In [178]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [179]:
df1 = pd.read_csv('ex1data2.txt', names=range(3))
df1.head()

0  1       2
0  2104  3  399900
1  1600  3  329900
2  2400  3  369000
3  1416  2  232000
4  3000  4  539900

In [180]:
y = np.matrix(df1[2])
y = np.reshape(y, (47, 1))
print(y.shape)

(47, 1)


In [181]:
X = np.matrix([df1[0], df1[1]])
X = X.transpose()
X.shape

(47, 2)

In [182]:
X

matrix([[2104,    3],
        [1600,    3],
        [2400,    3],
        [1416,    2],
        [3000,    4],
        [1985,    4],
        [1534,    3],
        [1427,    3],
        [1380,    3],
        [1494,    3],
        [1940,    4],
        [2000,    3],
        [1890,    3],
        [4478,    5],
        [1268,    3],
        [2300,    4],
        [1320,    2],
        [1236,    3],
        [2609,    4],
        [3031,    4],
        [1767,    3],
        [1888,    2],
        [1604,    3],
        [1962,    4],
        [3890,    3],
        [1100,    3],
        [1458,    3],
        [2526,    3],
        [2200,    3],
        [2637,    3],
        [1839,    2],
        [1000,    1],
        [2040,    4],
        [3137,    3],
        [1811,    4],
        [1437,    3],
        [1239,    3],
        [2132,    4],
        [4215,    4],
        [2162,    4],
        [1664,    2],
        [2238,    3],
        [2567,    4],
        [1200,    3],
        [ 852,    2],
        [1

In [183]:
m = len(y)
m

47

In [184]:
print("First 10 examples from the dataset: \n")
print(X[1:10], y[1:10])

First 10 examples from the dataset: 

[[1600    3]
 [2400    3]
 [1416    2]
 [3000    4]
 [1985    4]
 [1534    3]
 [1427    3]
 [1380    3]
 [1494    3]] [[329900]
 [369000]
 [232000]
 [539900]
 [299900]
 [314900]
 [198999]
 [212000]
 [242500]]


In [185]:
def featureNormalize(X):
    X_norm = X
    mu = np.zeros((1, X.shape[1]))
    sigma = np.zeros((1, X.shape[1]))

    mu = np.mean(X, axis=0)

    sigma = np.std(X, axis=0)

    X_norm = np.subtract(X_norm, mu)

    if(sigma.all() != 0): 
        X_norm = np.divide(X_norm, sigma)

    return X_norm, mu, sigma

In [186]:
X, mu, sigma = featureNormalize(X)

In [187]:
X.shape

(47, 2)

In [188]:
intercept = np.ones([m, 1])
intercept.shape

(47, 1)

In [189]:
X = np.append(intercept, X, axis=1)
X.shape

(47, 3)

In [190]:
X.shape

(47, 3)

In [191]:
alpha = 0.01
num_iters = 400
theta = np.zeros([3, 1])
theta

array([[0.],
       [0.],
       [0.]])

In [192]:
def computeCostMulti(X, y, theta):
    m = len(y)
    J = 0
    h = X*theta
    error = np.subtract(h, y)
    J = 1/(2*m) * np.sum(np.power(error, 2))
    return J

In [193]:
J = computeCostMulti(X, y, theta)
J

65591548106.45744

In [194]:
def gradientDescentMulti(X, y, theta, alpha, num_iters):
    m = len(y)
    J_history = np.zeros([num_iters, 1])
    for iter in range(num_iters):
        h = X*theta
        error = np.subtract(h, y)
        theta_change = alpha/m * (X.transpose() * error)
        theta = theta - theta_change
        J_history[iter] = computeCostMulti(X, y, theta)
    
    return theta, J_history


In [201]:
theta, J_history = gradientDescentMulti(X, y, theta, alpha, 1500)
theta

matrix([[340412.65957447],
        [109447.79646964],
        [ -6578.35485416]])

In [202]:
test1 = np.matrix([1650, 3])
test1 = featureNormalize(test1)[0]
test1 = np.append(np.ones([1, 1]), test1, axis=1)
predict1 = test1 * theta
print("For a 1650 sqft, 3 br house, we predict a price of %f" % (predict1))

For a 1650 sqft, 3 br house, we predict a price of 340412.659574


In [197]:
# df2 = pd.read_csv('ex1data2.txt', names=range(3))
# df2.head()
# y = np.matrix(df1[2])
# y = np.reshape(y, (47, 1))
# m = len(y)
# X = np.matrix([df1[0], df1[1]])
# X = X.transpose()
# X.shape

In [203]:
def normalEqn(X, y):
    theta = np.zeros([X.shape[1], 1])
    inverse = np.linalg.inv(X.transpose() * X)
    theta = inverse * X.transpose() * y
    return theta
    

In [204]:
theta = normalEqn(X, y)
theta

matrix([[340412.65957447],
        [109447.79646964],
        [ -6578.35485416]])

In [205]:
test2 = np.matrix([1650, 3])
test2 = featureNormalize(test2)[0]
test2 = np.append(np.ones([1, 1]), test2, axis=1)
predict2 = test2 * theta
print("For a 1650 sqft, 3 br house, we predict a price of %f" % (predict2))

For a 1650 sqft, 3 br house, we predict a price of 340412.659574
